rush:
  address:
    city: "Hà Nội"
    districts:
      - Ba Đình
      - Hoàn Kiếm
      - Hai Bà Trưng
      - Đống Đa
      - Cầu Giấy
      - Thanh Xuân
      - Long Biên
      - Hoàng Mai
      - Tây Hồ
      - Nam Từ Liêm
      - Bắc Từ Liêm
      - Hà Đông
