rush:
  address:
    city: "Hà Nội"
    districts:
      - Ba Đình
      - Hoàn Kiếm
      - Hai Bà Trưng
      - Đống Đa
      - Cầu Giay
      - Thanh Xuân
      - Long Biên
      - Hoàng Mai
      - Tây Hồ
      - Nam Tu Liem
      - Bac Tu Liem
      - Ha Dong
